### ISSUE TITLE
docker create ecs does not have --name flag

### ISSUE THREAD

**Issue by panslava** [anshrma/docker-compose-ecs-sample#1]
In README it mentions 

```
docker context create ecs --name FILL_ME_NAME
```

But running this line you get 

```
unknown flag: --name
```

Looks like `--name` flag needs to be removed, it works fine without it

**Comment by anshrma** [comment]
Thanks. Fixed it. This sample applications is now used in self paced workshop available at https://docker.awsworkshop.io/ , hence would encourage to use the instructions in the workshop
